version: 2
updates:
  # Maintain dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns: &react-deps
          - react
          - react-dom
          - react-is
          - react-test-renderer
          - @types/react
          - @types/react-dom
          - @types/react-is
  # Maintain dependencies for backend
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      react:
        patterns: *react-deps
  # maintain dependencies for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # maintain dependencies for Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
